model:
  # stabilityai/stable-diffusion-xl-refiner-1.0 | runwayml/stable-diffusion-v1-5 | common-canvas/CommonCanvas-XL-C
  # video: ali-vilab/text-to-video-ms-1.7b | guoyww/animatediff
  pretrained_model: runwayml/stable-diffusion-v1-5

prior_generation:
  class_prompt: a photo of a backpack
  output_npz: ../class_priors/backpack_class_priors.npz
  num_images: 200
  batch_size: 16
  num_inference_steps: 50
  guidance_scale: 7.5
  save_previews: true
  preview_dir: ../class_priors/backpack_previews

runtime:
  seed: 0

hydra:
  job:
    chdir: false
